quanlithuchi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls")),
]

web/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "web"
urlpatterns = [
    path("",views.home,name="home"),
    path('sign_up',views.sign_up, name='sign_up'),
    path('sign_in',views.sign_in, name='sign_in'),
    path('meun',views.meun, name='meun'),
    path('tien_thu', views.tien_thu,name='tien_thu'),
    path('tien_chi',views.tien_chi, name='tien_chi'),
    path('tong_ket_thu_chi',views.tong_ket_thu_chi, name='tong_ket_thu_chi'),
    path('bieu_do_thu',views.bieu_do_thu, name='bieu_do_thu'),
    path('bieu_do_chi',views.bieu_do_chi, name='bieu_do_chi'),
    path('nang_cap_vip',views.nang_cap_vip, name='nang_cap_vip'),
]

web/models.py
from django.db import models

# Create your models here.

web/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,"web/home.html")
def sign_in(request):
    return render(request,"web/sign_in.html")
def sign_up(request):
    return render(request,"web/sign_up.html")
def meun(request):
    return render(request,"web/meun.html")
def tien_thu(request):
    return render(request,"web/tien_thu.html")
def tien_chi(request):
    return render(request,"web/tien_chi.html")
def tong_ket_thu_chi(request):
    return render(request,"web/tong_ket_thu_chi.html")
def bieu_do_thu(request):
    return render(request,"web/bieu_do_thu.html")
def bieu_do_chi(request):
    return render(request,"web/bieu_do_chi.html")
def nang_cap_vip(request):
    return render(request,"web/nang_cap_vip.html")

Meun/templates/Meun/index.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="static/Meun/css/style.css">
    <style>
    body{
    background-color: #fcd1d1;
    font-family: system-ui;
    width: 100%;
    margin: 0;
}
.meun{
    margin-left: 5%;
    width:90%;
    box-shadow: 0 100px 10000px #49df41;
    position: relative;
}
.profile{
    background-color: #eabefe;
    margin:auto;
    padding:5px;
    display: grid;
    grid-template-columns: 25% 60%;
    column-gap: 5%; 
    row-gap: 5px;
}
.avatar img{
    width:200px;
    height:200px;
    object-fit: cover;
    border-radius: 50%;
}
.avatar{
    display: flex;
    margin-left: 30%;
    align-items: center;
}
.name{
    padding-left: 10px;
    border-left:1px solid #000;
}
.name .specialize{
    margin:5px;
    font-weight: bold;
    letter-spacing: 3px;
    margin-bottom: 40px;
}
.name .contact{
    padding:0;
    list-style: none;
}
.name .contact span{
    display: inline-block;
    background-color: #000;
    width:20px;
    height:20px;
    color:#fff;
    text-align: center;
    border-radius: 50%;
    font-size: small;
    margin-right: 20px;
}
.name .contact li{
    padding:5px 0;
    transform: translate(-40px);
    background-color: #E9E7EA;
}

.container{
    background-color: #edcaff;
    margin:auto;
    padding:30px;
    display: grid;
    grid-template-columns: 20% 20% 20%;
    height: 450px;
    padding-left: 15%;
    column-gap: 10%; 
    align-items: center;
}
.tien_thu{
    height: 200px;
    background-color: #f86c6c;
    box-shadow: 0 100px 1000px #d70a0a;
    text-align: justify;
}
.img1 {
    height: 200px;
    padding-top: 50px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("luong.jpg");
    background-size: 100%;
    
}
.img1 h1{
    margin-left: 10%;
    width: 80%;
    transform: translate(1px);
    transform: translate(0px);
    background-color: #E9E7EA;
    text-align: center;
    background-image: url("static/Meun/img/luong.jpg");
    background-size: 100%;
}
.tien_chi{
    height: 200px;
    background-color: #f86c6c;
    box-shadow: 0 100px 1000px #d70a0a;
    text-align: justify;
}
.img2 {
    height: 200px;
    padding-top: 50px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("luong.jpg");
    background-size: 100%;
    
}
.img2 h1{
    margin-left: 10%;
    width: 80%;
    transform: translate(1px);
    transform: translate(0px);
    background-color: #E9E7EA;
    text-align: center;
}
.tong_ket_thu_chi{
    height: 200px;
    background-color: #f86c6c;
    box-shadow: 0 100px 1000px #d70a0a;
    text-align: justify;
} 
.img3 {
    height: 200px;
    padding-top: 50px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("luong.jpg");
    background-size: 100%;
    
}
.img3 h1{
    margin-left: 10%;
    width: 80%;
    transform: translate(1px);
    transform: translate(0px);
    background-color: #E9E7EA;
    text-align: center;
}
.bieu_do_thu{
    height: 200px;
    background-color: #f86c6c;
    box-shadow: 0 100px 1000px #d70a0a;
    text-align: justify;
}
.img4 {
    height: 200px;
    padding-top: 50px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("luong.jpg");
    background-size: 100%;
    
}
.img4 h1{
    margin-left: 10%;
    width: 80%;
    transform: translate(1px);
    transform: translate(0px);
    background-color: #E9E7EA;
    text-align: center;
}
.bieu_do_chi{
    height: 200px;
    background-color: #f86c6c;
    box-shadow: 0 100px 1000px #d70a0a;
    text-align: justify;
}
.img5 {
    height: 200px;
    padding-top: 50px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("luong.jpg");
    background-size: 100%;
    
}
.img5 h1{
    margin-left: 10%;
    width: 80%;
    transform: translate(1px);
    transform: translate(0px);
    background-color: #E9E7EA;
    text-align: center;
}
.nang_cap_vip{
    height: 200px;
    background-color: #f86c6c;
    box-shadow: 0 100px 1000px #d70a0a;
    text-align: justify;
}
.img6 {
    height: 200px;
    padding-top: 50px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("luong.jpg");
    background-size: 100%;
    
}
.img6 h1{
    margin-left: 10%;
    width: 80%;
    transform: translate(1px);
    transform: translate(0px);
    background-color: #E9E7EA;
    text-align: center;
}
    </style>
</head>
<body>
<div class="meun">
    <div class="profile">
        <div class="avatar">
            <img src="static/Meun/img/meun.jpg" alt="">
        </div>
        <div class="name">
            <div class="specialize"><h2><center>Thông Tin Người Dùng</center></h2></div>
            <ul class="contact">
                <li>
                    <span>N</span> +...
                </li>
                <li>
                    <span>J</span> +..
                </li>
                <li>
                    <span>P</span> +...
                </li>
            </ul>
        </div>
    </div>
    <div class="container">
        <div class="tien_thu">
            <div class="img1">
                <a href="{% url 'tien_thu:index' %}"><h1>Tiền Thu</h1></a>
            </div>
        </div>
        <div class="tien_chi">
            <div class="img2">
                <a href="{% url 'tien_chi:index' %}"><h1>Tiền Chi</h1></a>
            </div>
            
        </div>
        <div class="tong_ket_thu_chi">
            <div class="img3">
                <a href="{% url 'tong_ket_thu_chi:index' %}"><h1>Tổng Kết thu chi</h1></a>
            </div>
            
        </div>
        <div class="bieu_do_thu">
            <div class="img4">
                <a href="{% url 'bieu_do_chi:index' %}"><h1>Biểu đồ thu</h1></a>
            </div>
            
        </div>
        <div class="bieu_do_chi">
            <div class="img5">
                <a href="{% url 'bieu_do_chi:index' %}"><h1>Biểu đồ chi</h1></a>
            </div>
            
        </div>
        <div class="nang_cap_vip">
            <div class="img6">
                <a href="{% url 'nang_cap_vip:index' %}"><h1>Nâng cấp VIP</h1></a>
            </div>
        </div>
    </div>
</div>
</body>
</html>

nang_cap_vip/templates/nang_cap_vip/index.html
<!DOCTYPE html>
<html>
<head>
<style>
*{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Roboto', sans-serif;
  }
  .flex{
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .meun{
    width: 100%;
    height: 100vh;
    background-color: #fcd1d1;;
  }
  .vip{
    background-color: #edcaff;
    width: 60%;
    height: 700px;
  }
.note{
    height: 50px;
}
.container{
    background-color: #ffffff;
    margin:auto;
    padding:30px;
    display: grid;
    grid-template-columns: 30% 30% 30%;
    height: 500px;
    column-gap: 5%; 
    align-items: center;
}
.a1ngay{
    height: 200px;
    background-color: #f86c6c;
    box-shadow: 0 100px 1000px #d70a0a;
    text-align: justify;
}
.img1 {
    height: 170px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("z4184044056779_9f9f52025cd592d4427dfa789747ae6c.jpg");
    background-size: 100%;
    
}
.a1tuan{
    height: 200px;
    background-color: #f86c6c;
    box-shadow: 0 100px 1000px #d70a0a;
    text-align: justify;
}
.img2 {
    height: 170px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("z4184044056779_9f9f52025cd592d4427dfa789747ae6c.jpg");
    background-size: 100%;
    
}
.a1thang{
    height: 200px;
    background-color: #f86c6c;
    box-shadow: 0 100px 1000px #d70a0a;
    text-align: justify;
} 
.img3 {
    height: 170px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("z4184044056779_9f9f52025cd592d4427dfa789747ae6c.jpg");
    background-size: 100%;
    
}
.a3thang{
    height: 200px;
    background-color: #f86c6c;
    text-align: justify;
}
.img4 {
    height: 170px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("z4184044056779_9f9f52025cd592d4427dfa789747ae6c.jpg");
    background-size: 100%;
    
}
.a6thang{
    height: 200px;
    background-color: #f86c6c;
    text-align: justify;
}
.img5 {
    height: 170px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("z4184044056779_9f9f52025cd592d4427dfa789747ae6c.jpg");
    background-size: 100%;
    
}
.a1nam{
    height: 200px;
    background-color: #f86c6c;
    text-align: justify;
}
.img6 {
    height: 170px;
    object-fit: cover;
    background-repeat: no-repeat;
    background-image: url("z4184044056779_9f9f52025cd592d4427dfa789747ae6c.jpg");
    background-size: 100%;
    
}
  /* modal-body */
  .modal-body{
    height: 150px;
    background: rgb(186, 228, 235);

  }

.cart-header {
    font-weight: bold;
    font-size: 1.25em;
    color: #333;
  }
  
  .cart-column {
    display: flex;
    align-items: center;
    border-bottom: 1px solid black;
    margin-right: 1.5em;
    padding-bottom: 10px;
    margin-top: 10px;
  }
  
  .cart-row {
    display: flex;
  }
  
  .cart-item {
    width: 45%;
  }
  
  .cart-price {
    width: 20%;
    font-size: 1.2em;
    color: #333;
  }
  
  .cart-quantity {
    width: 35%;
  }
  
  .cart-item-title {
    color: #333;
    margin-left: .5em;
    font-size: 1.2em;
  }
  
  .cart-item-image {
    width: 75px;
    height: auto;
    border-radius: 10px;
  }
  
  .btn-danger {
    color: white;
    background-color: #EB5757;
    border: none;
    border-radius: .3em;
    font-weight: bold;
  }
  
  .btn-danger:hover {
    background-color: #CC4C4C;
  }
  
  .cart-quantity-input {
    height: 34px;
    width: 50px;
    border-radius: 5px;
    border: 1px solid #56CCF2;
    background-color: #eee;
    color: #333;
    padding: 0;
    text-align: center;
    font-size: 1.2em;
    margin-right: 25px;
  }
  
  .cart-row:last-child {
    border-bottom: 1px solid black;
  }
  
  .cart-row:last-child .cart-column {
    border: none;
  }
  
  .cart-total {
    text-align: end;
    margin-top: 10px;
    margin-right: 10px;
  }
  
  .cart-total-title {
    font-weight: bold;
    font-size: 1.5em;
    color: black;
    margin-right: 20px;
  }
  
  .cart-total-price {
    color: #333;
    font-size: 1.1em;
  }
</style>
</head>
<body>
<div class="meun flex">
    <div class="vip">
        <div class="note flex">
            <h1><center>NÂNG CẤP VIP</center></h1>
        </div>
        <div class="container">
            <div class="a1ngay">
                <div class="img1">
                </div>
                <h3 class="flex">Gói ngày :5000VND</h3>
            </div>
            <div class="a1tuan">
                <div class="img2">
                </div>
                <h3 class="flex">Gói tuần :30000VND</h3>
            </div>
            <div class="a1thang">
                <div class="img3">
                </div>
                <h3 class="flex">Gói tháng :110000VND</h3>
            </div>
            <div class="a3thang">
                <div class="img4">
                </div>
                <h3 class="flex">Gói 3 tháng :300000VND</h3>
            </div>
            <div class="a6thang">
                <div class="img5">
                </div>
                <h3 class="flex">Gói 6 tháng :550000VND</h3>
            </div>
            <div class="a1nam">
                <div class="img6">
                </div>
                <h3 class="flex">Gói năm :1100000VND</h3>
            </div>
        </div>
        <div class="modal-body ">
            <div class="cart-row">
                <span class="cart-item cart-header cart-column">Gói VIP</span>
                <span class="cart-price cart-header cart-column">Giá</span>
                <span class="cart-quantity cart-header cart-column">Số Lượng</span>
            </div>
            <div class="cart-items">
                <div class="cart-row">
                    <div class="cart-item cart-column">
                        <span class="cart-item-title">1 tháng</span>
                    </div>
                    <span class="cart-price cart-column">110000đ</span>
                    <div class="cart-quantity cart-column">
                        <input class="cart-quantity-input" type="number" value="1">
                        <button class="btn btn-danger" type="button">Xóa</button>
                    </div>
                </div>
                <div class="cart-total">
                    <strong class="cart-total-title">Tổng Cộng:</strong>
                    <span class="cart-total-price">250000VND</span>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

web/templates/web/home.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="static/css/home.css" />
</head>
<body>
    <div class="note">
        <h1>MONEY MANAGER</h1>
    </div>
    <div class="container">
        <div class="sign_up">
            <a href="{% url 'web:sign_up' %}"><h1><center>Đăng kí</center></h1></a>
        </div>
    </div>
    <div class="container1">
        <div class="sign_in">
            <a href="{% url 'web:sign_in' %}"><h1><center>Đăng Nhập</center></h1></a>
        </div>
    </div>
    <div class="note1">
        <h3><center><marquee width="50%">Chào mừng bạn đến với trang web của chúng tôi.Chúc bạn có những trải nghiệp khó quên</marquee></center></h3>
    </div>
</body>
</html>

web/templates/web/meun.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="static/css/meun.css" />
</head>
<body>
<div class="home">
    <div class="profile">
        <div class="avatar">
            <img src="static/image/avt.jpg" alt="">
        </div>
        <div class="name">
            <div class="specialize"><h2><center>Thông Tin Người Dùng</center></h2></div>
            <div class="contact">
                <p>
                    <span>N</span> +...
                </p>
                <p>
                    <span>J</span> +..
                </p>
                <p>
                    <span>P</span> +...
                </p>
            </ul>
        </div>

        </div>
        <ul>
            <li class="dropdown">
                <a class="dropbtn"><span>Cài đặt</span></a>
                <div class="dropdown-content">
                    <a href="#">Thông tin cá nhân</a>
                    <a href="#">Cài đặt web</a>
                    <a href="{% url 'web:home' %}">Đăng xuất </a>
                </div>
            </li>
        </ul>
    </div>
    <div class="container">
        <div class="tien_thu">
            <div class="img">
                <a href="{% url 'web:tien_thu' %}">
                    <img src="static/image/meun.jpg"  alt="" class="img-thumbnail img-avt" >
                    <h2>Tiền Thu</h2></a>
            </div>
        </div>
        <div class="tien_chi">
            <div class="img">
                <a href="{% url 'web:tien_chi' %}">
                    <img src="static/image/meun.jpg"  alt="" class="img-thumbnail img-avt" >
                    <h2>Tiền Chi</h2></a>
            </div>
            
        </div>
        <div class="tong_ket_thu_chi">
            <div class="img">
                <a href="{% url 'web:tong_ket_thu_chi' %}">
                    <img src="static/image/meun.jpg"  alt="" class="img-thumbnail img-avt" >
                    <h2>Tổng Kết thu chi</h2></a>
            </div>
            
        </div>
        <div class="bieu_do_thu">
            <div class="img">
                <a href="{% url 'web:bieu_do_chi' %}">
                    <img src="static/image/meun.jpg"  alt="" class="img-thumbnail img-avt" >
                    <h2>Biểu đồ thu</h2></a>
            </div>
            
        </div>
        <div class="bieu_do_chi">
            <div class="img">
                <a href="{% url 'web:bieu_do_chi' %}">
                    <img src="static/image/meun.jpg"  alt="" class="img-thumbnail img-avt" >
                    <h2>Biểu đồ chi</h2></a>
            </div>
            
        </div>
        <div class="nang_cap_vip">
            <div class="img">
                <a href="{% url 'web:nang_cap_vip' %}">
                    <img src="static/image/meun.jpg"  alt="" class="img-thumbnail img-avt" >
                    <h2>Nâng cấp VIP</h2></a>
            </div>
        </div>
    </div>
</div>
</body>
</html>

web/templates/web/nang_cap_vip.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="static/css/nang_cap_vip.css" />
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <div class="container">
        <div class="center">
            
            <h2>PRODUCTS</h2>
            <div class="list">
                <div class="item" data-key="1">
                    <div class="img">
                        <img src="static/image/nang_cap_vip.jpg" alt="">
                    </div>
                    <div class="content">
                        <div class="title">Gói ngày</div>
                        <div class="des">
                            ...............
                        </div>
                        <div class="price">5000VND</div>
                        <input type="number" class="count" min="1" value="1">
                        <button class="add">Add to cart</button>
                        <button class="remove" onclick="Remove(1)"><i class="fa-solid fa-trash-can"></i></button>
                    </div>
                </div>

                <div class="item" data-key="2">
                    <div class="img">
                        <img src="static/image/nang_cap_vip.jpg" alt="">
                    </div>
                    <div class="content">
                        <div class="title">Gói Tuần</div>
                        <div class="des">
                            ...............
                        </div>
                        <div class="price">30000VND</div>
                        <input type="number" class="count" min="1" value="1">
                        <button class="add">Add to cart</button>
                        <button class="remove" onclick="Remove(2)"><i class="fa-solid fa-trash-can"></i></button>
                    </div>
                </div>

                <div class="item" data-key="3">
                    <div class="img">
                        <img src="static/image/nang_cap_vip.jpg" alt="">
                    </div>
                    <div class="content">
                        <div class="title">Gói tháng</div>
                        <div class="des">
                            ...............
                        </div>
                        <div class="price">110000VND</div>
                        <input type="number" class="count" min="1" value="1">
                        <button class="add">Add to cart</button>
                        <button class="remove" onclick="Remove(3)"><i class="fa-solid fa-trash-can"></i></button>
                    </div>
                </div>

                <div class="item" data-key="4">
                    <div class="img">
                        <img src="static/image/nang_cap_vip.jpg" alt="">
                    </div>
                    <div class="content">
                        <div class="title">Gói 3 tháng</div>
                        <div class="des">
                            ...............
                        </div>
                        <div class="price">300000VND</div>
                        <input type="number" class="count" min="1" value="1">
                        <button class="add">Add to cart</button>
                        <button class="remove" onclick="Remove(4)"><i class="fa-solid fa-trash-can"></i></button>
                    </div>
                </div>

                <div class="item" data-key="5">
                    <div class="img">
                        <img src="static/image/nang_cap_vip.jpg" alt="">
                    </div>
                    <div class="content">
                        <div class="title">Gói 6 tháng</div>
                        <div class="des">
                            ...............
                        </div>
                        <div class="price">550000VND</div>
                        <input type="number" class="count" min="1" value="1">
                        <button class="add">Add to cart</button>
                        <button class="remove" onclick="Remove(5)"><i class="fa-solid fa-trash-can"></i></button>
                    </div>
                </div>

                <div class="item" data-key="6">
                    <div class="img">
                        <img src="static/image/nang_cap_vip.jpg" alt="">
                    </div>
                    <div class="content">
                        <div class="title">Gói năm</div>
                        <div class="des">
                            ...............
                        </div>
                        <div class="price">1100000VND</div>
                        <input type="number" class="count" min="1" value="1">
                        <button class="add">Add to cart</button>
                        <button class="remove" onclick="Remove(6)"><i class="fa-solid fa-trash-can"></i></button>
                    </div>
                </div>
            </div>

        </div>
        <div class="cart" >
            <form action="{% url 'web:nang_cap_vip' %}">
                <div class="name">CART</div>
                <div class="listCart">

                </div>
                <div class="submit" >
                    <a><center><input type="submit" value="Mua"></center></a>
                </div>
            </form>
        </div>
    </div>
    <script src="static/js/nang_cap_vip.js"></script>
</body>
</html>

web/templates/web/sign_in.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tạo Trang sign_in</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="static/sign_in/css/style.css">
        <link rel="stylesheet" type="text/css" href="static/css/sign_in.css" />
</head>
<body>
    <section>
        <!--Kết Thúc Phần Hình Ảnh-->
        <!--Bắt Đầu Phần Nội Dung-->
        <div class="noi-dung">
            <div class="form">
                <h2>Trang Đăng Nhập</h2>

                <form action= "{% url 'web:meun' %}" onsubmit="return validate()">
                    <div class="input-form">
                        <span for="username">SDT Người Dùng</span>
                        <input type="text" id="username" name="">
                    </div>
                    <div class="input-form">
                        <span for="password">Mật Khẩu</span>
                        <input type="password" id="password" name="">
                    </div>
                    <div class="nho-dang-nhap">
                        <label><input type="checkbox" name=""> Nhớ Đăng Nhập</label>
                    </div>
                    <div class="input-form">
                        <a><input type="submit" value="Đăng Nhập"></a>
                    </div>
                    <div class="input-form">
                        <p>Bạn Chưa Có Tài Khoản?  <a href="{% url 'web:sign_up' %}">Đăng Ký</a></p>
                    </div>
                </form>

                <h3>Đăng Nhập Bằng Mạng Xã Hội</h3>
                
                <ul class="icon-dang-nhap">
                    <li><i class="fa fa-facebook" aria-hidden="true"></i></li>
                    <li><i class="fa fa-google" aria-hidden="true"></i></li>
                    <li><i class="fa fa-twitter" aria-hidden="true"></i></li>
                </ul>
            </div>
        </div>
        <!--Kết Thúc Phần Nội Dung-->
    </section>
    <script src="static/js/sign_in.js"></script>
</body>
</html>

web/templates/web/sign_up.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tạo Trang sign_in</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/sign_up.css" />

</head>
<body>
    <section>
        <!--Kết Thúc Phần Hình Ảnh-->
        <!--Bắt Đầu Phần Nội Dung-->
        <div class="noi-dung">
            <div class="form">
                <h2>Trang Đăng kí</h2>

                <form action="{% url 'web:sign_in' %}">
                    <div class="input-form">
                        <span>Họ Tên Người Dùng</span>
                        <input type="text" name="">
                    </div>
                    <div class="input-form">
                        <span>email</span>
                        <input type="email" name="">
                    </div>
                    <div class="input-form">
                        <span>Tuổi Người Dùng</span>
                        <input type="number" name="">
                    </div>
                    <div class="input-form">
                        <span for="username">SDT Người Dùng</span>
                        <input type="text" id="username" name="">
                    </div>
                    <div class="input-form">
                        <span for="password">Mật Khẩu</span>
                        <input type="password" id="password" name="">
                    </div>
                    <div class="input-form">
                        <span>Nhập Lại Mật Khẩu</span>
                        <input type="password" name="">
                    </div>
                    <div class="nho-dang-nhap">
                        <label><input type="checkbox" name=""> Lưu Đăng Nhập</label>
                    </div>
                    <div class="input-form">
                        <input type="submit" value="Đăng Kí">
                    </div>
                    <div class="input-form">
                        <p>Bạn đã Có Tài Khoản?  <a href="{% url 'web:sign_in' %}">Đăng Nhập</a></p>
                    </div>
                </form>

                <h3>Đăng kí Bằng Mạng Xã Hội</h3>

                <ul class="icon-dang-nhap">
                    <li><i class="fa fa-facebook" aria-hidden="true"></i></li>
                    <li><i class="fa fa-google" aria-hidden="true"></i></li>
                    <li><i class="fa fa-twitter" aria-hidden="true"></i></li>
                </ul>
                
            </div>
        </div>
        <!--Kết Thúc Phần Nội Dung-->
    </section>
</body>
</html>